eclipse-fog05/fog05

fog05/api.py
fog05/fosagent.py
plugins/KVMLibvirt/KVMLibvirt_plugin.py
plugins/LXD/LXD_plugin.py
plugins/brctl/brctl_plugin.py
plugins/native/NativeEntityInstance.py
plugins/native/native_plugin.py
setup.py

Due to some problems in Cyclone DDS we are moving to a self made data sharing middleware for which we have more control.
This makes faster the communication between nodes.

Migration to another data sharing platform

---

plugins/KVMLibvirt/KVMLibvirt_plugin.py
plugins/LXD/LXD_plugin.py
plugins/brctl/brctl_plugin.py

Reaction on other plugin

---

fog05/api.py
plugins/KVMLibvirt/KVMLibvirt_plugin.py
plugins/KVMLibvirt/templates/create_config_drive.sh
plugins/KVMLibvirt/templates/vendor_data.yaml
plugins/LXD/LXD_plugin.py
plugins/brctl/brctl_plugin.py
plugins/brctl/templates/dnsmasq.sh
plugins/brctl/templates/vxlan_creation.sh
plugins/brctl/templates/vxlan_destroy.sh
plugins/linux/scripts/default_gw.sh
plugins/linux/scripts/manage_hosts.sh
setup.py

Fixes in LCM of Entities
Fixes in various plugins
Fixes in APIs

Various fixes after migration to different data sharing platform

---

setup_api.py

added setup_api.py for single api installation

---

plugins/KVMLibvirt/KVMLibvirt_plugin.py
plugins/LXD/LXD_plugin.py

grace shutdown lxd containers and kvm vms

---

plugins/LXD/LXDEntity.py
plugins/LXD/LXDEntityInstance.py
plugins/LXD/LXD_plugin.py

added custom device attachment in lxd container

---

fog05/api.py

added network.nodes in entity manifest

---

plugins/native/native_plugin.py

added check if instance exists during stop

---

plugins/native/native_plugin.py

changed stopping workflow

---

Makefile
fog05/interfaces/ResourceOrchestratorPlugin.py

added RO and RM plugin interfaces

---

fog05/DLogger.py

Logging facility uses Syslog if the agent runs in quiet mode

Update logging facility

---

fog05/fosagent.py
plugins/LXD/LXD_plugin.py

updated in agent and lxd plugin

---

fog05/api.py
plugins/LXD/LXD_plugin.py
setup.py

updated api and lxd plugin to manage images

---

plugins/LXD/LXD_plugin.py

Fixed the possibility do add images or use images defined inside the descriptor of the lxd container

LXD Plugin fixes on image managment

---

plugins/OVS/OVS_plugin.json
plugins/OVS/OVS_plugin.py
plugins/OVS/__init__.py
src/python/fog05/interfaces/NetworkPlugin.py

First version. OVS as network plugin

OVS plugin

---

src/api/python/rest_api/Makefile
src/api/python/rest_api/fog05rest/fimerrors.py
src/api/python/rest_api/setup.py

Added custom exceptions to REST API in order to be used by ETSI OSM vimconn

FIM Rest API Improvement 

---

src/utils/generate_mec_orchestrator.sh
src/utils/python/mec_mm1/Makefile

Updated the mec orchestrator generation script to be able to use binaries and added a flag to use build version

Update MEC Orchestrator Script

---

fos_install.sh
install_fos_lxd.sh
src/utils/python/rest_proxy/Makefile
src/utils/python/rest_proxy/fosrest.service
src/utils/python/rest_proxy/src/service.json

Added autoinstallation script that install all the dependencies a configure a single node fog05, with YAKS and LXD

Added auto-install script

---

src/utils/python/rest_proxy/src/service.py

Verify the type of the `request.data` before converting it to dict using `json.loads`

Fixing issue #92

---

fos-plugins/constraint/constraint_plugin
fos-plugins/linux/linux_plugin
fos-plugins/windows/windows_plugin

Replacing some `logger.error` with `logger.info`, this was a mistake, they were supposed to be info from the beginning

Solving #93

---

fos-plugins/linux/linux_plugin

Updated the node id retrevial from Linux plugin in order to retrieve a standart UUID with dashes.

fixing #83

---

src/im/ocaml/fos-im/fdu.atd
src/im/python/yang/fos/fdud.yang
src/im/python/yang/fos/fdur.rec.yang
src/im/python/yang/fos/vnetd.yang
src/im/python/yang/fos/vnetr.rec.yang
src/im/python/yang/mec/appd-base.yang
src/im/python/yang/mec/appd.yang
src/im/python/yang/mec/meao-types.yang

Align of the two IM modules, fixes #86

Align the pyhton IM module with the OCaml one

---

INSTALL.md
install_cli.sh

Updated INSTALL.md with inforamtion on how to install the CLI
Added installation script for the CLI

Added installation script for the CLI interface

---

fos-plugins/LXD/LXD_plugin

fix in LXD plugin when using images from lxd repository

---

etc/systemd/stop.sh
fos-plugins/LXD/LXD_plugin
fos-plugins/linuxbridge/Makefile
fos-plugins/linuxbridge/linuxbridge_plugin
src/agent/fos-agent/fos_agent.ml
src/api/python/api/fog05/yaks_connector.py
src/core/ocaml/fos-core/yaks_connector.ml
src/im/ocaml/fos-im/fos_types.atd

Some fixes all over the place in LXD, LinuxBridge and APIs

Fixes in LXD plugin, LinuxBridge plugin, APIs

---

fos-plugins/LXD/LXD_plugin
fos-plugins/linuxbridge/linuxbridge_plugin
src/agent/fos-agent/fos_agent.ml
src/api/python/api/fog05/fimapi.py
src/api/python/api/fog05/yaks_connector.py
src/core/ocaml/fos-core/yaks_connector.ml

This implements API updates to create and remove Floating IPs
Solves typos in LXD plugin logging.
Partially implements https://github.com/eclipse/fog05/issues/111

Creation of floating IPs, Fix typos in LXD plugin logging

---

fos-plugins/linuxbridge/linuxbridge_plugin
install_fos_lxd.sh
src/api/python/api/setup.py

Fix dependency version on yaks, mvar

---

fos-plugins/LXD/LXD_plugin

fix in LXD monitoring method

---

fos_install.sh
install_fos_lxd.sh

fix in installation scripts

---

fos-plugins/LXD/LXD_plugin
src/agent/fos-agent/fos_agent.ml
src/api/python/api/fog05/fimapi.py
src/api/python/api/fog05/yaks_connector.py

updates and fixes in pyhton api and agent

---

fos-plugins/LXD/LXD_plugin
fos-plugins/LXD/LXD_plugin.json

Added configuration of the storage pool for LXD plugin

---

src/api/python/rest_api/Makefile
src/api/python/rest_api/fog05rest/__init__.py
src/api/python/rest_api/fog05rest/fimapi.py
src/api/python/rest_api/setup.py

updated fog05rest python api to work with python3

---

src/api/go/fog05-go/runtime_plugin_fdu.go

Added interface for RuntimePluginFDU

---

src/agent/fos-agent/fos_agent.ml
src/api/go/fog05-go/runtime_plugin_fdu.go
src/api/go/fog05-go/yaks_connector.go

Revert "Fix Go API to use interfaces "

---

src/agent/fos-agent/fos_agent.ml
src/api/go/fog05-go/runtime_plugin.go
src/api/go/fog05-go/runtime_plugin_fdu.go
src/api/go/fog05-go/yaks_connector.go

Using interfaces in Go API for Runtime Plugin

Go API improvement 

---

etc/yaks.service

fix in service file to fix #165

---

BUILD.md
CONTRIBUTORS.rst

Update zenoh and yaks dependencies in BUILD.md

---

BUILD.md

updated submodules for use repositories with dependencies fixed

---

BUILD.md
Makefile
etc/yaks.service

fixing makefile and yaks service file

---

.gitmodules
.travis.yml

Preparing the release 0.1.0, updating submodules to branch 0.1.x

Preparing 0.1.0 Release

---

src/utils/python/rest_proxy/src/service.py

fixing #198

---

Jenkinsfile

Setting up Jenkins build
